package com.himmerland.hero.domain.tenancies;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class TenancyTest {

    @Test
    void convenienceConstructor_setsFieldsAndGeneratesId() {
        Tenancy tenancy = new Tenancy(
            "Dept A",
            "Street 1",
            "City",
            "1234"
        );

        assertEquals("Dept A", tenancy.getDepartmentName());
        assertEquals("Street 1", tenancy.getAddress());
        assertEquals("City", tenancy.getCity());
        assertEquals("1234", tenancy.getPostalCode());
        assertNotNull(tenancy.getId(), "Id should be generated by IdentifiableBase");
    }

    @Test
    void defaultConstructor_generatesIdAndAllowsSetters() {
        Tenancy tenancy = new Tenancy();
        String generatedId = tenancy.getId();

        tenancy.setDepartmentName("Dept B");
        tenancy.setAddress("Street 2");
        tenancy.setCity("Town");
        tenancy.setPostalCode("5678");

        assertEquals(generatedId, tenancy.getId(), "Default constructor should keep generated id");
        assertEquals("Dept B", tenancy.getDepartmentName());
        assertEquals("Street 2", tenancy.getAddress());
        assertEquals("Town", tenancy.getCity());
        assertEquals("5678", tenancy.getPostalCode());
    }

    @Test
    void setId_propagatesToIdentifiableBase() {
        Tenancy tenancy = new Tenancy("Dept C", "Street 3", "Village", "9999");
        tenancy.setId("costum-id");

        assertEquals("costum-id", tenancy.getId(), "setId should propagate to identifiable base");
    }
}
