package com.himmerland.hero.domain.departments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.himmerland.hero.service.helperclasses.id.IdentifiableBase;

public class Department extends IdentifiableBase  {
    private String Name;
    private String Email;

    public Department() {
        super();
        // ID will be auto-generated by IdentifiableBase
    }

    @JsonCreator
    public Department(@JsonProperty("id") String id, 
                      @JsonProperty("name") String name, 
                      @JsonProperty("email") String email) {
        super();
        this.Name = name;
        this.Email = email;
        // Sync the Id with IdentifiableBase if provided, otherwise use auto-generated
        if (id != null && !id.isBlank()) {
            super.setId(id);
        }
    }
    
    public String getId() {
        return super.getId();
    }

    public String getName() {
        return Name;
    }

    public String getEmail() {
        return Email;
    }

    public void setId(String id) {
        if (id != null && !id.isBlank()) {
            super.setId(id);
        }
    }

    public void setName(String name) {
        this.Name = name;
    }

    public void setEmail(String email) {
        this.Email = email;
    }
}