package com.himmerland.hero.service.tenancies;

import com.himmerland.hero.domain.tenancies.Tenancy;
import com.himmerland.hero.service.repositories.TenancyRepository;
import com.himmerland.hero.service.departments.DepartmentService;

import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

@Service
public class TenancyService {
    private final TenancyRepository repository;
    private final DepartmentService departmentService;

    public TenancyService(Path dataDir, DepartmentService departmentService) {
        this.repository = new TenancyRepository(dataDir);
        this.departmentService = departmentService;
    }

    public List<TenancyDTO> findAll() {
        return repository.findAll().stream()
            .map(TenancyDTO::fromDomain)
            .collect(Collectors.toList());
    }

    public TenancyDTO getTenancy(String id) {
        validateId(id);
        return repository.findById(id)
            .map(TenancyDTO::fromDomain)
            .orElseThrow(() -> new IllegalArgumentException("Tenancy not found: " + id));
    }

    public TenancyDTO createTenancy(TenancyDTO dto) {
        Objects.requireNonNull(dto, "Create payload cannot be null");

        // Resolve departmentId from departmentName if needed
        String resolvedDepartmentId = resolveDepartmentId(dto);

        // Convert DTO to domain object (ID will be auto-generated by IdentifiableBase)
        TenancyDTO dtoWithoutId = new TenancyDTO(
            null, // ID will be auto-generated
            dto.meterNumber(),
            resolvedDepartmentId, // Use resolved department ID
            null, // Clear departmentName
            dto.tenancyNumber(),
            dto.address(),
            dto.city(),
            dto.postalCode()
        );
        
        Tenancy tenancy = dtoWithoutId.toDomain();
        
        // Save and convert back to DTO
        Tenancy saved = repository.save(tenancy);
        return TenancyDTO.fromDomain(saved);
    }

    public TenancyDTO updateTenancy(TenancyDTO dto) {
        Objects.requireNonNull(dto, "Update payload cannot be null");
        validateId(dto.id());

        Tenancy existing = repository.findById(dto.id())
            .orElseThrow(() -> new IllegalArgumentException("Tenancy not found: " + dto.id()));

        if (dto.meterNumber() != null && !dto.meterNumber().isBlank()) {
            existing.setMeterNumber(dto.meterNumber());
        }

        // Resolve departmentId from departmentName if needed
        String resolvedDepartmentId = resolveDepartmentId(dto);
        if (resolvedDepartmentId != null && !resolvedDepartmentId.isBlank()) {
            existing.setDepartmentId(resolvedDepartmentId);
        }
        
        if (dto.tenancyNumber() != null && !dto.tenancyNumber().isBlank()) {
            existing.setTenancyNumber(dto.tenancyNumber());
        }

        if (dto.address() != null && !dto.address().isBlank()) {
            existing.setAddress(dto.address());
        }
        
        if (dto.city() != null && !dto.city().isBlank()) {
            existing.setCity(dto.city());
        }

        if (dto.postalCode() != null && !dto.postalCode().isBlank()) {
            existing.setPostalCode(dto.postalCode());
        }

        Tenancy updated = repository.save(existing);
        return TenancyDTO.fromDomain(updated);
    }

    public void deleteTenancy(String id) {
        validateId(id);
        repository.deleteById(id);
    }

    private void validateId(String id) {
        if (id == null || id.isBlank()) {
            throw new IllegalArgumentException("Id cannot be null or blank");
        }
    }

    private String resolveDepartmentId(TenancyDTO dto) {
        // If departmentId is provided, use it
        if (dto.departmentId() != null && !dto.departmentId().isBlank()) {
            return dto.departmentId();
        }
        
        // If departmentName is provided, try to find the department by name
        if (dto.departmentName() != null && !dto.departmentName().isBlank()) {
            return departmentService.findAll().stream()
                .filter(dept -> dept.getName() != null && dept.getName().equals(dto.departmentName()))
                .findFirst()
                .map(dept -> dept.getId())
                .orElse(dto.departmentName()); // Fallback: assume it's actually an ID if not found
        }
        
        return null;
    }
}