package com.himmerland.hero.service.tenancies;

import com.himmerland.hero.domain.tenancies.Tenancy;
import com.himmerland.hero.repositories.TenancyRepository;
import org.springframework.stereotype.Service;

import java.nio.file.Path;
import java.util.List;
import java.util.Objects;

@Service
public class TenancyService {
    private final TenancyRepository repository;

    public TenancyService(Path dataDir) {
        this.repository = new TenancyRepository(dataDir);
    }

    public List<Tenancy> findAll() {
        return repository.findAll();
    }

    public Tenancy getTenancy(String id) {
        validateId(id);
        return repository.findById(id)
            .orElseThrow(() -> new IllegalArgumentException("Tenancy not found: " + id));
    }

    public Tenancy createTenancy(TenancyDTO dto) {
        Objects.requireNonNull(dto, "Create payload cannot be null");

        // Check if tenancy already exists
        if (dto.id() != null && !dto.id().isBlank()) {
            repository.findById(dto.id()).ifPresent(existing -> {
                throw new IllegalArgumentException("Tenancy already exists: " + dto.id());
            });
        }

        Tenancy tenancy = new Tenancy(
            dto.meterNumber(),
            dto.departmentId(),
            dto.tennancyNumber(),
            dto.address(),
            dto.city(),
            dto.postalCode()
        );

        // Set ID if provided, otherwise it will be auto-generated by IdentifiableBase
        if (dto.id() != null && !dto.id().isBlank()) {
            tenancy.setId(dto.id());
        }

        if (dto.active() != null) {
            tenancy.setActive(dto.active());
        }

        return repository.save(tenancy);
    }

    public Tenancy updateTenancy(TenancyDTO dto) {
        Objects.requireNonNull(dto, "Update payload cannot be null");
        validateId(dto.id());

        Tenancy existing = getTenancy(dto.id());

        if (dto.meterNumber() != null && !dto.meterNumber().isBlank()) {
            existing.setMeterNumber(dto.meterNumber());
        }

        if (dto.departmentId() != null && !dto.departmentId().isBlank()) {
            existing.setDepartmentId(dto.departmentId());
        }
        
        if (dto.tennancyNumber() != null && !dto.tennancyNumber().isBlank()) {
            existing.setTennancyNumber(dto.tennancyNumber());
        }

        if (dto.address() != null && !dto.address().isBlank()) {
            existing.setAddress(dto.address());
        }
        
        if (dto.city() != null && !dto.city().isBlank()) {
            existing.setCity(dto.city());
        }

        if (dto.postalCode() != null && !dto.postalCode().isBlank()) {
            existing.setPostalCode(dto.postalCode());
        }
        
        if (dto.active() != null) {
            existing.setActive(dto.active());
        }

        repository.save(existing);
        return existing;
    }

    public void deleteTenancy(String id) {
        validateId(id);
        repository.deleteById(id);
    }

    public void validateId(String id) {
        if (id == null || id.isBlank()) {
            throw new IllegalArgumentException("Id cannot be null or blank");
        }
    }
}