package com.himmerland.hero.domain.meters;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class MeterTest {

    @Test
    void allArgsConstructor_setsFieldAndGeneratesId() {
        Meter meter = new Meter("m-123", "HEAT", "Main St 1");

        assertEquals("m-123", meter.getMeterNumber());
        assertEquals("HEAT", meter.getConsumptionType());
        assertEquals("Main St 1", meter.getAddress());
        assertNotNull(meter.getId(), "Id should be generated by IdentifiableBase");
    }

    @Test
    void setters_UpdateFieldsAndPreserveIdentity() {
        Meter meter = new Meter();
        String originalId = meter.getId();

        meter.setMeterNumber("m-456");
        meter.setConsumptionType("WATER");
        meter.setAddress("Elm St 2");

        assertEquals("m-456", meter.getMeterNumber());
        assertEquals("WATER", meter.getConsumptionType());
        assertEquals("Elm St 2", meter.getAddress());
        assertEquals(originalId, meter.getId(), "Mutations should not change identity");
    }
}
